# -*- coding: utf-8 -*-
"""COL761_A3_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/117blvbCJNLR-NQ9mt13HXaGL3fnTsGqG
"""

import numpy as np
import random
import matplotlib.pyplot as plt

#Variables
point_dimensions=[1,2,4,8,16,32,64]
distance_method=[1,2,np.inf]
Ratio=[[],[],[]]

for i in range(7):
  points=np.round(np.random.uniform(0,1.0,size=(1000000,point_dimensions[i])),5)
  rng = np.random.default_rng()
  query_points= rng.choice(points,100,axis=0,replace=False)
  # print(query_points.shape)
  boolean = np.array([True]*100)
  average_ratio=[0,0,0]
  for j in range(100):
    X= np.subtract(points,query_points[j])
    for k in range(3):
      distances=np.linalg.norm(X,ord=distance_method[k],axis=1)
      boolean= distances > 0
      average_ratio[k] += (np.max(distances[boolean])/np.min(distances[boolean]))
  average_rat=np.array(average_ratio)/100.0
  # print(average_rat)
  for k in range(3):
    Ratio[k].append(average_rat[k])

def draw_plot(x,y1,y2,y3,log_scaled=False):
    if(log_scaled):
      plt.yscale('log')
    plt.title('average distance ratios(using L1,L2,L_inf method) vs dimension of points')
    plt.plot(x, y1, label='L1', marker='o', linestyle='-')
    plt.plot(x, y2, label='L2', marker='o', linestyle='-')
    plt.plot(x, y3, label='L '+str(np.inf), marker='o', linestyle='-')
    plt.grid(True)
    plt.xlabel('Dimension of points')
    if(log_scaled):
      plt.ylabel('Average Ratios (This axis is scaled to log10)')
    else:
      plt.ylabel('Average Ratios')
    #scaling use both
    # plt.yscale('log10')
    plt.legend()
    if(log_scaled):
      plt.savefig('Q1_plot_log_scaled.png')
    else:
      plt.savefig('Q1_plot.png')
    plt.show()
draw_plot(point_dimensions,Ratio[0],Ratio[1],Ratio[2])
draw_plot(point_dimensions,Ratio[0],Ratio[1],Ratio[2],log_scaled=True)